# Generated by Django 4.2.7 on 2023-11-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_information",
            name="about_user",
            field=models.TextField(
                null=True, verbose_name="معرفی فیلد های کاری و از اینجور حرف ها "
            ),
        ),
    ]
