# Generated by Django 4.2.7 on 2023-11-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="pictrue",
            field=models.FileField(
                null=True, upload_to="Post_Image/", verbose_name="عکس سر تیتر "
            ),
        ),
    ]
