# Generated by Django 4.2.7 on 2023-11-14 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_pictrue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="pictrue",
            new_name="picture",
        ),
    ]
