# Generated by Django 4.2.7 on 2023-11-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_pictrue_post_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="time_to_read",
            field=models.IntegerField(
                null=True, verbose_name="مدت زمان لازم برای خواندن پست "
            ),
        ),
    ]
