# Generated by Django 4.2.7 on 2023-11-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_post_time_to_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Comments", models.TextField(verbose_name="کامنت")),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام و نام خانوادگی"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "webiste",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="آدرس وبسایت ",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "کامنت های پست ها ",
                "db_table": "Comments",
            },
        ),
    ]
