# Generated by Django 4.2.7 on 2023-11-15 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
                verbose_name="پست ",
            ),
        ),
    ]
