# Generated by Django 4.2.7 on 2023-11-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_comments_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="webiste",
            field=models.CharField(
                max_length=50, null=True, verbose_name="آدرس وبسایت "
            ),
        ),
    ]
