# Generated by Django 4.2.7 on 2023-11-15 08:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_rename_comments_comments_of_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments_of_post",
            old_name="webiste",
            new_name="website",
        ),
    ]
