# Generated by Django 4.2.7 on 2023-11-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_comments_of_post_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="INSTAGRAM_POST",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="نام پست اینستاگرامی"),
                ),
                (
                    "picture",
                    models.FileField(
                        upload_to="Instagram_Posts_Image/",
                        verbose_name="عکس پست های اینستاگرامی",
                    ),
                ),
                ("slug", models.SlugField(verbose_name="آدرس پست اینستاگرامی")),
            ],
            options={
                "verbose_name_plural": "پست های اینستاگرامی",
                "db_table": "INSTAGRAM_POST",
            },
        ),
    ]
