# Generated by Django 4.2.7 on 2023-11-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_instagram_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABOUT_WEBSITE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, verbose_name="عنوان")),
                (
                    "picture",
                    models.FileField(
                        upload_to="ABOUT_WEBSITE_IMAGE/", verbose_name="عکس"
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
            ],
            options={
                "verbose_name_plural": "توضیحات وبسایت",
                "db_table": "ABOUT_WEBSITE",
            },
        ),
    ]
