# Generated by Django 4.2.7 on 2023-11-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_contact_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="SOCIAL_MEDIA_WEBSITE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="فیسبوک"
                    ),
                ),
                (
                    "twitter",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="توئیتر"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="لینکدین"
                    ),
                ),
                (
                    "github",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="گیتهاب"
                    ),
                ),
                (
                    "youtube",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="یوتیوب"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "شبکه های اجتماهی وبسایت مهندسی صنایع",
                "db_table": "SOCIAL_MEDIA_WEBSITE",
            },
        ),
    ]
