# Generated by Django 4.2.7 on 2023-11-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_social_media_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABOUT_US_MODEL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_mission_mine_title",
                    models.CharField(max_length=100, verbose_name="عنوان متن "),
                ),
                ("text1", models.TextField(verbose_name="متن ")),
                (
                    "picture1",
                    models.FileField(
                        upload_to="ABOUT_US_PICTURE_IMAGE/", verbose_name="عکس 1 "
                    ),
                ),
                (
                    "main_mission_of_company1",
                    models.CharField(max_length=50, verbose_name="1عنوان"),
                ),
                (
                    "text_main_mission_of_company1",
                    models.TextField(verbose_name="1متن ماموریت کمپانی"),
                ),
                (
                    "main_mission_of_company2",
                    models.CharField(max_length=50, verbose_name="2عنوان"),
                ),
                (
                    "main_mission_of_company3",
                    models.CharField(max_length=50, verbose_name="3عنوان"),
                ),
                (
                    "text_main_mission_of_company3",
                    models.TextField(verbose_name="3متن ماموریت کمپانی"),
                ),
                (
                    "great_tem_title",
                    models.CharField(max_length=100, verbose_name="عنوان"),
                ),
                ("text_great_team", models.TextField(verbose_name="متن تیم")),
                (
                    "picture_great_team",
                    models.FileField(
                        upload_to="PICTURE_GREAT_TEAM_IMAGE/", verbose_name="عکس تیم"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "درباره تیم ما ",
                "db_table": "ABOUT_US_MODEL",
            },
        ),
        migrations.AlterModelOptions(
            name="social_media_website",
            options={"verbose_name_plural": "شبکه های اجتماعی وبسایت مهندسی صنایع"},
        ),
    ]
