# Generated by Django 4.2.7 on 2023-11-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0016_post_status_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="picture2",
            field=models.FileField(
                blank=True, null=True, upload_to="Post_Image/", verbose_name="عکس 2 "
            ),
        ),
    ]
