# Generated by Django 4.2.7 on 2023-11-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_post_picture2"),
    ]

    operations = [
        migrations.AddField(
            model_name="about_us_model",
            name="title2",
            field=models.CharField(max_length=100, null=True, verbose_name="هنوان 2 "),
        ),
    ]
