# Generated by Django 4.2.7 on 2023-11-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_about_us_model_title2"),
    ]

    operations = [
        migrations.AddField(
            model_name="about_us_model",
            name="text_main_mission_of_company2",
            field=models.TextField(null=True, verbose_name="2متن ماموریت کمپانی"),
        ),
        migrations.AlterField(
            model_name="about_us_model",
            name="title2",
            field=models.CharField(max_length=100, null=True, verbose_name="عنوان 2 "),
        ),
    ]
