# Generated by Django 4.2.7 on 2023-11-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0019_about_us_model_text_main_mission_of_company2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="about_us_model",
            name="text4",
            field=models.CharField(
                max_length=100, null=True, verbose_name="متن سابسکرایب "
            ),
        ),
        migrations.AddField(
            model_name="about_us_model",
            name="text_5",
            field=models.TextField(null=True, verbose_name="متن 5 "),
        ),
        migrations.AddField(
            model_name="about_us_model",
            name="title5",
            field=models.CharField(max_length=100, null=True, verbose_name="عنوان 5"),
        ),
    ]
